### ISSUE TITLE
Precision of "value" in transaction too low for Ethereum's 18 decimal balances

### ISSUE THREAD

**Issue by dietersommer** [icopen/evm_utils_ic#1]
The transaction types, e.g., `transaction_1559.rs`, encode the `value` only as a `u64`. However, this is not enough for accurately representing the number of tokens to be transferred in an Ethereum transaction as this is specified with 18 decimals in Ethereum (they use 32-byte / 256-bit numbers here). Assuming that the `u64` value represents Wei, an `u18` only allows to represent around up to 18 Ether.

Would it make sense to use type with a larger precision for representing the `value`? Technically, the same argument holds for the other numbers in the transaction, like the gas fee, but is's less of an issue here.

**Comment by stopak** [comment]
It is a good point, I can increase it to 256-bit number.

**Comment by dietersommer** [comment]
Sounds like a good idea. Do you think that all the values that are encoded by Ethereum with 256 bits should be changed? The others like gas price are less crucial, but still it would be cleaner to have all be 256 bit.

**Comment by stopak** [comment]
I've changed to 256 bit for all transaction types. All tests are passing :). I've also updated the production canister.
